// Generated by gencpp from file mavros_msgs/TrustMoments.msg
// DO NOT EDIT!


#ifndef MAVROS_MSGS_MESSAGE_TRUSTMOMENTS_H
#define MAVROS_MSGS_MESSAGE_TRUSTMOMENTS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace mavros_msgs
{
template <class ContainerAllocator>
struct TrustMoments_
{
  typedef TrustMoments_<ContainerAllocator> Type;

  TrustMoments_()
    : header()
    , trust_x(0.0)
    , trust_y(0.0)
    , trust_z(0.0)
    , moments_x(0.0)
    , moments_y(0.0)
    , moments_z(0.0)  {
    }
  TrustMoments_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , trust_x(0.0)
    , trust_y(0.0)
    , trust_z(0.0)
    , moments_x(0.0)
    , moments_y(0.0)
    , moments_z(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _trust_x_type;
  _trust_x_type trust_x;

   typedef double _trust_y_type;
  _trust_y_type trust_y;

   typedef double _trust_z_type;
  _trust_z_type trust_z;

   typedef double _moments_x_type;
  _moments_x_type moments_x;

   typedef double _moments_y_type;
  _moments_y_type moments_y;

   typedef double _moments_z_type;
  _moments_z_type moments_z;





  typedef boost::shared_ptr< ::mavros_msgs::TrustMoments_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavros_msgs::TrustMoments_<ContainerAllocator> const> ConstPtr;

}; // struct TrustMoments_

typedef ::mavros_msgs::TrustMoments_<std::allocator<void> > TrustMoments;

typedef boost::shared_ptr< ::mavros_msgs::TrustMoments > TrustMomentsPtr;
typedef boost::shared_ptr< ::mavros_msgs::TrustMoments const> TrustMomentsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavros_msgs::TrustMoments_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavros_msgs::TrustMoments_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mavros_msgs::TrustMoments_<ContainerAllocator1> & lhs, const ::mavros_msgs::TrustMoments_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.trust_x == rhs.trust_x &&
    lhs.trust_y == rhs.trust_y &&
    lhs.trust_z == rhs.trust_z &&
    lhs.moments_x == rhs.moments_x &&
    lhs.moments_y == rhs.moments_y &&
    lhs.moments_z == rhs.moments_z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mavros_msgs::TrustMoments_<ContainerAllocator1> & lhs, const ::mavros_msgs::TrustMoments_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mavros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mavros_msgs::TrustMoments_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavros_msgs::TrustMoments_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavros_msgs::TrustMoments_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavros_msgs::TrustMoments_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavros_msgs::TrustMoments_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavros_msgs::TrustMoments_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavros_msgs::TrustMoments_<ContainerAllocator> >
{
  static const char* value()
  {
    return "71d543861c7d601b68d75a139508b0bd";
  }

  static const char* value(const ::mavros_msgs::TrustMoments_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x71d543861c7d601bULL;
  static const uint64_t static_value2 = 0x68d75a139508b0bdULL;
};

template<class ContainerAllocator>
struct DataType< ::mavros_msgs::TrustMoments_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavros_msgs/TrustMoments";
  }

  static const char* value(const ::mavros_msgs::TrustMoments_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavros_msgs::TrustMoments_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"float64 trust_x\n"
"float64 trust_y\n"
"float64 trust_z\n"
"\n"
"float64 moments_x\n"
"float64 moments_y\n"
"float64 moments_z\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::mavros_msgs::TrustMoments_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavros_msgs::TrustMoments_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.trust_x);
      stream.next(m.trust_y);
      stream.next(m.trust_z);
      stream.next(m.moments_x);
      stream.next(m.moments_y);
      stream.next(m.moments_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrustMoments_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavros_msgs::TrustMoments_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavros_msgs::TrustMoments_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "trust_x: ";
    Printer<double>::stream(s, indent + "  ", v.trust_x);
    s << indent << "trust_y: ";
    Printer<double>::stream(s, indent + "  ", v.trust_y);
    s << indent << "trust_z: ";
    Printer<double>::stream(s, indent + "  ", v.trust_z);
    s << indent << "moments_x: ";
    Printer<double>::stream(s, indent + "  ", v.moments_x);
    s << indent << "moments_y: ";
    Printer<double>::stream(s, indent + "  ", v.moments_y);
    s << indent << "moments_z: ";
    Printer<double>::stream(s, indent + "  ", v.moments_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVROS_MSGS_MESSAGE_TRUSTMOMENTS_H
